### ISSUE TITLE
Hospedagem

### ISSUE THREAD

**Issue by santosvini** [angelicaalbuquerque/frontangie#3]
Ola Angélica, onde vc hospedou o seu site-port?

Gostaria de ter esse dominio também(.dev)

**Comment by angelicaalbuquerque** [comment]
Oi, @santosvini! 

Primeiramente, muito obrigada por ter visto meu projeto e vir falar comigo.

O domínio eu comprei no [Google Domains](https://domains.google/intl/pt-BR_br/). Já a hospedagem é via [Vercel](https://vercel.com/). 

Eu optei pela plataforma Vercel por ser gratuita para o tamanho do meu projeto; ter uma excelente integração com o Github; ser realmente simples e rápida (quando você pisca, o deploy já foi) e fornecer certificado SSL de graça também (para ter um domínio **.dev** no ar isso é necessário, pois é um namespace seguro).

Qualquer dúvida, pode falar comigo. 🙂 

Boa sorte e bons estudos!

**Comment by santosvini** [comment]
> Oi, @santosvini!
> 
> Primeiramente, muito obrigada por ter visto meu projeto e vir falar comigo.
> 
> O domínio eu comprei no [Google Domains](https://domains.google/intl/pt-BR_br/). Já a hospedagem é via [Vercel](https://vercel.com/).
> 
> Eu optei pela plataforma Vercel por ser gratuita para o tamanho do meu projeto; ter uma excelente integração com o Github; ser realmente simples e rápida (quando você pisca, o deploy já foi) e fornecer certificado SSL de graça também (para ter um domínio **.dev** no ar isso é necessário, pois é um namespace seguro).
> 
> Qualquer dúvida, pode falar comigo. 🙂
> 
> Boa sorte e bons estudos!

Sensacional Angelica, to fazendo o meu também e vi o domínio como algo interessante e chamativo, ajuda na divulgação do trabalho, a Vercel eu conheço e tenho alguns projetos simples hospedado lá, Domains da Google, super dica boa, obrigado
